name: CI & CD

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ '1.16' ]
        os: [ 'ubuntu-20.04' ]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: ${{ matrix.go }}
      - name: Check source is Go fmted
        run: make -f Makefile.ci check-fmt
      - name: Check source is Go fmt simplified
        run: make -f Makefile.ci check-fmt-simplify
      - name: Run staticcheck
        run: make -f Makefile.ci staticcheck
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: |
          go build

